#!/bin/bash
for i in {1..100}
do
mkdir -p DDM$i
touch DDM$i/time_till_now.txt
cd DDM$i/
echo "nanoseconds since 1970-01-01 00:00:00 UTC:" >> time_till_now.txt
echo "< $(date +%s%N) >" >> time_till_now.txt
cd ..
done

